import './style.css'

export default function Html() {
  return (
    <div>
    <h1>Html</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae nisi, eaque a, suscipit accusantium quas eum consequatur voluptatem, aut est atque perspiciatis exercitationem blanditiis quibusdam veniam laboriosam! Quia quibusdam libero eveniet consequuntur laborum quo dolorem inventore quaerat tempore error dicta, culpa provident nisi vero dolorum eaque atque quod, amet impedit perspiciatis at assumenda asperiores quas. Quibusdam ducimus debitis odit nemo tempore ipsam neque dolor quisquam quaerat similique nam beatae natus dolore eligendi magnam voluptatem aliquam praesentium, minima blanditiis vel sunt distinctio incidunt facilis. Tempora eos expedita error est corporis nulla obcaecati eligendi laborum dignissimos corrupti aliquid vel aspernatur similique, recusandae, id ad aut eius architecto repudiandae voluptatem et quos dolorum laudantium! Voluptas incidunt facilis aperiam ducimus eos tempore labore repellendus. Harum ab voluptatem dignissimos fugiat, totam sed velit vero atque quibusdam rem nemo incidunt nihil nesciunt reprehenderit delectus nisi enim odio maiores cumque. Laborum nisi sed iste doloribus itaque? Facilis quam possimus neque maiores iusto quidem autem odio, vitae accusamus non unde quis ad! Velit facilis sapiente aliquam dolorem! Adipisci numquam consectetur tenetur? Vero officia odit dicta molestias? Fugiat, ducimus adipisci, atque beatae pariatur aliquam, quo quisquam quos minus consectetur impedit modi eos dolores voluptate. Aliquam laborum odio dolores suscipit illum architecto veritatis animi, pariatur neque necessitatibus, omnis rem repellat adipisci distinctio commodi quisquam exercitationem hic nobis. Ipsa laborum asperiores amet deserunt. Nostrum, nam similique eius eos in modi doloribus suscipit at excepturi ut, deserunt voluptates officiis aliquid iusto. Nobis inventore neque, repudiandae unde impedit at nesciunt cumque placeat minima, dolorum dolores nisi. Natus molestiae maxime tempore facere quisquam. Vel quae vero, rem alias laboriosam porro est ad molestias laborum excepturi asperiores, sint iure. Quod alias fugiat ipsam provident quo excepturi modi voluptate quasi obcaecati iure, deserunt cupiditate. Cum, dolor iusto impedit ad qui soluta architecto sed quod accusamus iure illum natus libero! Eveniet error officiis voluptatem maiores excepturi temporibus molestias, quae consequatur omnis illum, veniam rem nam ipsa quis!</p>
    </div>
  )
}

